FROM ubuntu:22.04

ENV MANAGE_USB_POWER=$MANAGE_USB_POWER \
   RUPCON_HOST=$RUPCON_HOST \
   RUPCON_PORT=$RUPCON_PORT \
   FPGA_LOADER=$FPGA_LOADER

RUN apt-get update && \
    apt-get install -y \
    wget \
    tar \
    sudo \
    libusb-1.0-0 \
    libavahi-client3 \
    libavahi-core7 \
    libdaemon0 \
    bind9-host \
    avahi-daemon

RUN apt-get install -y \
    python3.9 \
    python3-pip   && \
    pip install Flask \
    pip install pyserial

RUN pip install requests

RUN apt-get install -y \
    usbutils \
    nano

WORKDIR /home/softwares

COPY softwares/ /home/softwares

RUN sudo dpkg -i digilent.adept.runtime_2.27.9-amd64.deb \
 && sudo dpkg -i digilent.adept.utilities_2.7.1-amd64.deb

WORKDIR /home/fpga-loader

CMD ["/bin/bash"]