version: '3.8'

services:
  fpga-loader:
    image: fpga-loader-image
    container_name: fpga-loader-container
    command: python3 ./main.py
    build:
      context: ./docker
      dockerfile: dockerfile
    tty: true
    ports:
      - 8000:8000
    volumes:
      - ./src:/home/src
    devices:
      - "/dev/bus/usb/:/dev/bus/usb/"
      - "/dev/ttyUSB0:/dev/ttyUSB0"
