version: '3.8'

services:
  fpga-loader:
    image: fpga-loader-image
    container_name: fpga-loader-container
    command: python3 ./fpga-loader.py
    build:
      context: ./fpga-loader
      dockerfile: dockerfile
    tty: true
    ports:
      - 8000:8000
    env_file:
      - .env
    privileged: true
    volumes:
      - ./fpga-loader:/home/fpga-loader
      - /dev/:/dev/
    networks:
      - fpga-loader-network
  
  RUPCon:
    image: rupcon-image
    container_name: rupcon-container
    command: python3 ./RUPCon.py
    build:
      context: ./remoteUSBPowerControl
      dockerfile: dockerfile
    tty: true
    ports:
      - 8001:8001
    environment:
      - RUPCON_PORT=${RUPCON_PORT}
      - ID_VENDOR_ARDUINO=${ID_VENDOR_ARDUINO}
      - ID_PRODUCT_ARDUINO=${ID_PRODUCT_ARDUINO}
    privileged: true
    volumes:
      - ./remoteUSBPowerControl:/home/remoteUSBPowerControl
    networks:
      - fpga-loader-network
    devices:
      - /dev/:/dev/

  ReTiCap:
    image: reticap-image
    container_name: reticap-container
    command: python3 ./reticap.py
    build:
      context: ./realTimeVideoCapture
      dockerfile: dockerfile
    tty: true
    ports:
      - 5000:5000
    env_file:
      - .env
    privileged: true
    volumes:
      - ./realTimeVideoCapture:/home/realTimeVideoCapture
      - /dev/:/dev/
    networks:
      - fpga-loader-network

networks:
  fpga-loader-network: