FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y

RUN apt-get install -y \
    python3.9 \
    python3-pip   && \
    pip install opencv-python-headless \
    pip install Flask

WORKDIR /home/realTimeVideoCapture

CMD ["/bin/bash"]