# Generated by Django 4.2 on 2023-08-23 08:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PowerSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('type_ps', models.CharField(choices=[('USB', 'USB'), ('EXTERNAL', 'EXTERNAL')], max_length=8, verbose_name='Type of Power Supply')),
                ('voltage', models.DecimalField(blank=True, decimal_places=2, help_text='Value must be informed in Volts (V)', max_digits=5, null=True)),
                ('max_current', models.DecimalField(blank=True, decimal_places=3, help_text='Value must be informed in Ampere (A)', max_digits=5, null=True)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Power supply',
                'verbose_name_plural': 'Power Suppliers',
                'db_table': 'power_supply',
                'ordering': ['num'],
            },
        ),
        migrations.CreateModel(
            name='SerialCollector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('type_sc', models.CharField(choices=[('INTEGRATED', 'INTEGRATED'), ('EXTERNAL', 'EXTERNAL')], max_length=10, verbose_name='Type of Serial Collector')),
                ('available', models.BooleanField(default=True)),
                ('connected_power_supply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.powersupply')),
            ],
            options={
                'verbose_name': 'Serial Collector',
                'verbose_name_plural': 'Serial Collectors',
                'db_table': 'serial_collector',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FPGA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50)),
                ('available', models.BooleanField(default=True)),
                ('connected_power_supply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.powersupply')),
                ('connected_serial_collector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.serialcollector')),
            ],
            options={
                'verbose_name': 'FPGA',
                'verbose_name_plural': 'FPGAs',
                'db_table': 'fpga',
                'ordering': ['name'],
            },
        ),
    ]
